### PR TITLE
Add SimpleAsset10

### PR DESCRIPTION
**Pull request by attilaaf**
**Changes:**

- Add `Utils.writeVarMinimalPushdata` to write minimally encoded bytes
- Add SuperAsset10.scrypt smart contract and superAsset10.js deployment example.

 
**Learn more:**
- Announcement: https://blog.matterpool.io/launch-of-superasset-sa10-nft-smart-contract-for-bitcoin/
- SuperAsset white paper: https://bitcoinfiles.org/t/d6c18189966ea060452bcf59157235f2e15df3abf7383d9d450acff69cf29181
- Github: https://github.com/MatterPool/superasset-js

**Example transactions:**

Deploy: https://whatsonchain.com/tx/afd702c8ccd5b3193f7be0afaace551430593b2e1af7264908e003f63bd5883f

Transfer (mint with JSON paylod update): https://whatsonchain.com/tx/9a731acb3ef5af7ec97a14725f481aa9cac69beba7567c596e155cd1993f2905

Transfer (Update with hex payload): https://whatsonchain.com/tx/b402d74aced39ef78489977b6dff0baadb0756f3f7a09de30af3fc9b7ff579a7

Transfer (Update with empty payload): https://whatsonchain.com/tx/e2253ec3f66f23b21726eae65f93d1a002e12413dceb7809ee7423a4794bc328

Melt: https://whatsonchain.com/tx/24e81130d115a67975c4558c3a617e0fdcb1def9126f8748b7c1072b0430e9b0

### CODE REVIEW

**Review by xhliu — CHANGES_REQUESTED** [review]
🔥 Well done!

Just one nit, can you please remove unrelated changes such as `spvToken.scrypt`?

**Comment by attilaaf** [comment]
@xhliu Thank you! Changes done, now only includes the 2 files I added

**Comment by attilaaf** [comment]
Thanks @xhliu 

Done, just replaced with the 3 files added now.

**Review by xhliu — APPROVED** [review]
👍

**Pull request merged**
